### ISSUE TITLE
dev:h5 运行出错

### ISSUE THREAD

**Issue by chinadbo** [bozaigao/Taro-demo#1]
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/4602050/66710777-8782c780-edb1-11e9-9055-5a4d237f5a33.png">

<img width="656" alt="image" src="https://user-images.githubusercontent.com/4602050/66710765-6b7f2600-edb1-11e9-98a4-7e300e539df6.png">

**Comment by bozaigao** [comment]
看报错信息是第三方库的报错信息,建议将node_modules和package-lock.json删除后重新执行npm I安装
