### ISSUE TITLE
微信小程序上面，底部下面四个导航栏没有居中

### ISSUE THREAD

**Issue by panrongfu** [bozaigao/Taro-demo#2]
1、微信小程序上面，底部下面四个导航栏没有居中
2、VM30:1 thirdScriptError
o.__props.onPress is not a function; [Component] Event Handler Error @ compoments/touchable-button/index#(anonymous)
TypeError: o.__props.onPress is not a function

**Comment by bozaigao** [comment]
你可以微调下呢
