### ISSUE TITLE
微信小程序跑不起来

### ISSUE THREAD

**Issue by yanminmin** [bozaigao/Taro-demo#7]
![image](https://user-images.githubusercontent.com/1975597/77222399-b174bd00-6b8d-11ea-93a5-1f4c698218f3.png)
![image](https://user-images.githubusercontent.com/1975597/77222402-b76a9e00-6b8d-11ea-880f-b996bd42b14f.png)
![image](https://user-images.githubusercontent.com/1975597/77222404-bf2a4280-6b8d-11ea-9948-a4f120fa9d56.png)
![image](https://user-images.githubusercontent.com/1975597/77222409-c5b8ba00-6b8d-11ea-8e00-e04e11fe4c61.png)
![image](https://user-images.githubusercontent.com/1975597/77222414-d5d09980-6b8d-11ea-88e2-a084929f1f57.png)
不知道为啥就是启动不了，麻烦指点下

**Comment by yanminmin** [comment]
补充下  现在的环境改为taro1.3.18了，不是最新的taro2.0.7

**Comment by bozaigao** [comment]
你检查下全局安装的taro版本是不是1.3.18的

**Comment by yanminmin** [comment]
多谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"波仔糕"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月21日(星期六) 下午4:23
收件人:&nbsp;"bozaigao/Taro-demo"<Taro-demo@noreply.github.com&gt;;
抄送:&nbsp;"晏敏敏"<5706046@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bozaigao/Taro-demo] 微信小程序跑不起来 (#7)





 
你检查下全局安装的taro版本是不是1.3.18的

**Comment by yanminmin** [comment]
搞定了，是找不到路径。

**Comment by yanminmin** [comment]
搞定了，小程序找不到路径




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "波仔糕"<notifications@github.com&gt;; 
发送时间: 2020年3月21日(星期六) 下午4:23
收件人: "bozaigao/Taro-demo"<Taro-demo@noreply.github.com&gt;; 
抄送: "晏敏敏"<5706046@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bozaigao/Taro-demo] 微信小程序跑不起来 (#7)





 
你检查下全局安装的taro版本是不是1.3.18的
